## Updating Data Exercise

**This exercise uses the `netflix_titles.csv` dataset**

In [106]:
# read in the netflix_titles.csv dataset.  Make sure to tell pandas to use the correct separator character!

import pandas as pd
netflix = pd.read_csv('C:/Users/RomanHrytsenko/Documents/DataAnalysis/data/netflix_titles.csv', sep = '|')

In [107]:
# set the index to be the "show_id" (inplace)

netflix.set_index('show_id', inplace = True)
netflix

         Unnamed: 0  ...                                        description
show_id              ...
s1                0  ...  As her father nears the end of his life, filmm...
s2                1  ...  After crossing paths at a party, a Cape Town t...
s3                2  ...  To protect his family from a powerful drug lor...
s4                3  ...  Feuds, flirtations and toilet talk go down amo...
s5                4  ...  In a city of coaching centers known to train I...
...             ...  ...                                                ...
s8803          8802  ...  A political cartoonist, a crime reporter and a...
s8804          8803  ...  While living alone in a spooky town, a young g...
s8805          8804  ...  Looking to survive in a world taken over by zo...
s8806          8805  ...  Dragged from civilian life, a former superhero...
s8807          8806  ...  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [108]:
# Find the row with the id of s2202 and set its director to "Greg Whiteley"

netflix.loc[['s2202'], ['director']] = 'Greg Whiteley'
netflix.loc[['s2202']]

         Unnamed: 0     type          title  ...   duration   listed_in                                        description
show_id                                      ...
s2202          2201  TV Show  Last Chance U  ...  5 Seasons  Docuseries  In a docuseries set at one of NCAA football's ...

[1 rows x 12 columns]

In [109]:
#Update the "duration" of the shows with index s2881 and s3601 to be "GONE TOO SOON"

netflix.loc[['s2881', 's3601'], ['duration']] = "GONE TOO SOON"
netflix.loc[['s2881', 's3601']]

         Unnamed: 0  ...                                        description
show_id              ...
s2881          2880  ...  Angsty Syd navigates high school awkwardness, ...
s3601          3600  ...  In 1980s LA, a crew of misfits reinvent themse...

[2 rows x 12 columns]

In [110]:
#rename the release_year column to "release_yr" in place

netflix.rename(columns = {'release_year': 'release_yr'}, inplace = True)
netflix

         Unnamed: 0  ...                                        description
show_id              ...
s1                0  ...  As her father nears the end of his life, filmm...
s2                1  ...  After crossing paths at a party, a Cape Town t...
s3                2  ...  To protect his family from a powerful drug lor...
s4                3  ...  Feuds, flirtations and toilet talk go down amo...
s5                4  ...  In a city of coaching centers known to train I...
...             ...  ...                                                ...
s8803          8802  ...  A political cartoonist, a crime reporter and a...
s8804          8803  ...  While living alone in a spooky town, a young g...
s8805          8804  ...  Looking to survive in a world taken over by zo...
s8806          8805  ...  Dragged from civilian life, a former superhero...
s8807          8806  ...  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [111]:
#rename the title column to "Title" and director colunm to "Director" in place

mapper = {'title': 'Title', 'director': 'Director'}

netflix.rename(columns = mapper, inplace = True)
netflix

         Unnamed: 0  ...                                        description
show_id              ...
s1                0  ...  As her father nears the end of his life, filmm...
s2                1  ...  After crossing paths at a party, a Cape Town t...
s3                2  ...  To protect his family from a powerful drug lor...
s4                3  ...  Feuds, flirtations and toilet talk go down amo...
s5                4  ...  In a city of coaching centers known to train I...
...             ...  ...                                                ...
s8803          8802  ...  A political cartoonist, a crime reporter and a...
s8804          8803  ...  While living alone in a spooky town, a young g...
s8805          8804  ...  Looking to survive in a world taken over by zo...
s8806          8805  ...  Dragged from civilian life, a former superhero...
s8807          8806  ...  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [112]:
# Find the show called "Evil"
# Change its index label to s6666 inplace

netflix[netflix['Title'] == 'Evil']
netflix.rename(index = {'s1907': 's6666'}, inplace = True)

In [113]:
netflix[netflix['Title'] == 'Evil']

         Unnamed: 0     type Title  ...  duration  listed_in                                        description
show_id                             ...
s6666          1906  TV Show  Evil  ...  1 Season  TV Dramas  A forensic psychologist partners with a Cathol...

[1 rows x 12 columns]

In [114]:
# In the rating column, please replace all instances of "UR" and "NR" with "No Rating".  Don't do it inplace!

netflix['rating'].replace(['UR', 'NR'], ['No Rating', 'No Rating']).value_counts()

rating
TV-MA        3207
TV-14        2160
TV-PG         863
R             799
PG-13         490
TV-Y7         334
TV-Y          307
PG            287
TV-G          220
No Rating      83
G              41
TV-Y7-FV        6
NC-17           3
74 min          1
84 min          1
66 min          1
Name: count, dtype: int64

In [115]:
# Add a new column "is_fav" and set it to False for all rows
# Update the "is_fav" column to True for the titles in my list of favs (provided below)
favs = ["Young Royals", "Dark", "Big Mouth", "BoJack Horseman", "The Queen's Gambit", "American Vandal", "Russian Doll", "Godless"]

netflix['is_fav'] = False
netflix.loc[netflix['Title'].isin(favs), 'is_fav'] = True

In [116]:
netflix['is_fav'].value_counts()

is_fav
False    8799
True        8
Name: count, dtype: int64